services:
  api:
    build:
      context: ./
      dockerfile: ./WebAPIWithDocker/Dockerfile
    image: mywebapi:dev
    volumes:
      - C:\Users\mnizama\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\mnizama\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 54540:80
      - 54541:443
    networks:
      - net
    depends_on:
      - db
  db:
    build:
      context: ./
      dockerfile: ./dbDockerfile
    image: mydb:dev
    volumes:
      - mydb:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - net
networks:
  net:
volumes:
  mydb: